export const BIZLINE_LIST = './bizline/listEnable';
export const BIZLINE_ADD = './bizline/create';
export const BIZLINE_EDIT = './bizline/edit';
export const BIZLINE_DEL = './bizline/delete';
export const BIZLINE_ALL_LIST = './bizline/listAuthBizLine';
export const USER_LIST = './user/listEnable';
export const USER_ADD = './user/create';
export const USER_EDIT = './user/edit';
export const USER_DEL = './user/delete';
export const ROLE_LIST = './role/listByBizLineId';
export const ROLE_ADD = './role/create';
export const ROLE_EDIT = './role/edit';
export const ROLE_DEL = './role/delete';
export const FUNC_LIST = './func/listByBizLineId';
export const FUNC_ADD = './func/create';
export const FUNC_EDIT = './func/edit';
export const FUNC_DEL = './func/delete';
export const FUNC_TREE= './func/listByParentId';
export const USER_TO_ROLE_SAVE = './user/listRoleId'; // 用户绑定角色
export const USER_TO_ROLE = './user/bindRoles'; // 用户已绑定的角色
export const ROLE_TO_FUNC = './role/listFuncId'; // 角色已绑定的功能id
export const ROLE_TO_FUNC_SAVE = './role/bindFuncs'; // 角色绑定功能保存接口

